[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
allow_paths = ["../source/lib"]
remappings = [
    "@openzeppelin/contracts/=../source/lib/openzeppelin-contracts/contracts/",
    "forge-std/=../source/lib/forge-std/src/",
    "@gluwa/asc-contracts/=lib/asc-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
